# Generated by Django 3.1 on 2020-08-22 07:33

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=models.SET(blog.models.get_default_cate), on_delete=models.SET(blog.models.get_default_cate), related_name='related_posts', to='blog.category', verbose_name='Category'),
        ),
    ]
